// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TUP.MundialTPI.DatosEF;

#nullable disable

namespace TUP.MundialTPI.DatosEF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260625172657_AgregarBorradoLogico")]
    partial class AgregarBorradoLogico
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TUP.MundialTPI.Entidades.Estadio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Estadios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacidad = 92542,
                            Ciudad = "Pasadena",
                            ImagenUrl = "https://media.telemundo51.com/2025/03/argentinabrasil.jpg?quality=85&strip=all&resize=1200%2C675",
                            Nombre = "Rose Bowl",
                            Pais = "Estados Unidos"
                        },
                        new
                        {
                            Id = 2,
                            Capacidad = 82500,
                            Ciudad = "East Rutherford",
                            ImagenUrl = "https://www.directvsports.com/__export/1720258446592/sites/dsports/img/2024/07/06/20240706_063405942_732035_0_1533.jpg_554688468.jpg",
                            Nombre = "MetLife Stadium",
                            Pais = "Estados Unidos"
                        },
                        new
                        {
                            Id = 3,
                            Capacidad = 87523,
                            Ciudad = "Ciudad de México",
                            ImagenUrl = "https://media.tycsports.com/files/2023/11/10/644251/mexico-se-enfrenta-ante-la-visita-alemania-por-la-fecha-1-del-grupo-f_862x485_wmk.webp",
                            Nombre = "Estadio Azteca",
                            Pais = "México"
                        },
                        new
                        {
                            Id = 4,
                            Capacidad = 30000,
                            Ciudad = "Toronto",
                            ImagenUrl = "https://www.americanfootballinternational.com/wp-content/uploads/ITA-CAN.jpg",
                            Nombre = "BMO Field",
                            Pais = "Canadá"
                        });
                });

            modelBuilder.Entity("TUP.MundialTPI.Entidades.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EntradasDisponibles")
                        .HasColumnType("integer");

                    b.Property<string>("EquipoLocal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EquipoVisitante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EstadioId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EstadioId");

                    b.ToTable("Partidos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EntradasDisponibles = 1240,
                            EquipoLocal = "Argentina",
                            EquipoVisitante = "Brasil",
                            EstadioId = 1,
                            Estado = "Activo",
                            Fase = "Final",
                            FechaHora = new DateTime(2026, 6, 14, 18, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            EntradasDisponibles = 500,
                            EquipoLocal = "Francia",
                            EquipoVisitante = "España",
                            EstadioId = 2,
                            Estado = "Activo",
                            Fase = "Semifinal",
                            FechaHora = new DateTime(2026, 6, 15, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            EntradasDisponibles = 0,
                            EquipoLocal = "México",
                            EquipoVisitante = "Alemania",
                            EstadioId = 3,
                            Estado = "Activo",
                            Fase = "Cuartos de final",
                            FechaHora = new DateTime(2026, 6, 20, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            EntradasDisponibles = 3200,
                            EquipoLocal = "Canadá",
                            EquipoVisitante = "Italia",
                            EstadioId = 4,
                            Estado = "Activo",
                            Fase = "Fase de Grupos",
                            FechaHora = new DateTime(2026, 6, 25, 14, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TUP.MundialTPI.Entidades.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PartidoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.Property<string>("TipoEntrada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PartidoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("TUP.MundialTPI.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Email = "admin@mundial.com",
                            Nombre = "Admin User",
                            PasswordHash = "$2a$11$yD/piJffVpHeaIO5MxdNWOA3JItPuyf5hh3j1w94c/R924kGmQq6.",
                            Rol = "admin"
                        });
                });

            modelBuilder.Entity("TUP.MundialTPI.Entidades.Partido", b =>
                {
                    b.HasOne("TUP.MundialTPI.Entidades.Estadio", "Estadio")
                        .WithMany()
                        .HasForeignKey("EstadioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estadio");
                });

            modelBuilder.Entity("TUP.MundialTPI.Entidades.Ticket", b =>
                {
                    b.HasOne("TUP.MundialTPI.Entidades.Partido", "Partido")
                        .WithMany()
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TUP.MundialTPI.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partido");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
