// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TUP.MundialTPI.DatosEF;

#nullable disable

namespace TUP.MundialTPI.DatosEF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("TUP.Mundial.Entidades.Estadio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Estadios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacidad = 92542,
                            Ciudad = "Pasadena",
                            ImagenUrl = "https://images.unsplash.com/photo-1518605368461-1e1e108d1f2d?q=80&w=1000&auto=format&fit=crop",
                            Nombre = "Rose Bowl",
                            Pais = "Estados Unidos"
                        },
                        new
                        {
                            Id = 2,
                            Capacidad = 82500,
                            Ciudad = "East Rutherford",
                            ImagenUrl = "https://images.unsplash.com/photo-1508344928928-7165b67de128?q=80&w=1000&auto=format&fit=crop",
                            Nombre = "MetLife Stadium",
                            Pais = "Estados Unidos"
                        },
                        new
                        {
                            Id = 3,
                            Capacidad = 87523,
                            Ciudad = "Ciudad de México",
                            ImagenUrl = "https://images.unsplash.com/photo-1522778147829-047360bdc7f6?q=80&w=1000&auto=format&fit=crop",
                            Nombre = "Estadio Azteca",
                            Pais = "México"
                        },
                        new
                        {
                            Id = 4,
                            Capacidad = 30000,
                            Ciudad = "Toronto",
                            ImagenUrl = "https://images.unsplash.com/photo-1628891435222-065922031e0b?q=80&w=1000&auto=format&fit=crop",
                            Nombre = "BMO Field",
                            Pais = "Canadá"
                        });
                });

            modelBuilder.Entity("TUP.Mundial.Entidades.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntradasDisponibles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EquipoLocal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EquipoVisitante")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EstadioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EstadioId");

                    b.ToTable("Partidos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EntradasDisponibles = 1240,
                            EquipoLocal = "Argentina",
                            EquipoVisitante = "Brasil",
                            EstadioId = 1,
                            Fase = "Final",
                            FechaHora = new DateTime(2026, 6, 14, 18, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            EntradasDisponibles = 500,
                            EquipoLocal = "Francia",
                            EquipoVisitante = "España",
                            EstadioId = 2,
                            Fase = "Semifinal",
                            FechaHora = new DateTime(2026, 6, 15, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            EntradasDisponibles = 0,
                            EquipoLocal = "México",
                            EquipoVisitante = "Alemania",
                            EstadioId = 3,
                            Fase = "Cuartos de final",
                            FechaHora = new DateTime(2026, 6, 20, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            EntradasDisponibles = 3200,
                            EquipoLocal = "Canadá",
                            EquipoVisitante = "Italia",
                            EstadioId = 4,
                            Fase = "Fase de Grupos",
                            FechaHora = new DateTime(2026, 6, 25, 14, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TUP.Mundial.Entidades.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("TEXT");

                    b.Property<int>("PartidoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoEntrada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PartidoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("TUP.Mundial.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@mundial.com",
                            Nombre = "Admin User",
                            PasswordHash = "$2a$11$yD/piJffVpHeaIO5MxdNWOA3JItPuyf5hh3j1w94c/R924kGmQq6.",
                            Rol = "admin"
                        });
                });

            modelBuilder.Entity("TUP.Mundial.Entidades.Partido", b =>
                {
                    b.HasOne("TUP.Mundial.Entidades.Estadio", "Estadio")
                        .WithMany()
                        .HasForeignKey("EstadioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estadio");
                });

            modelBuilder.Entity("TUP.Mundial.Entidades.Ticket", b =>
                {
                    b.HasOne("TUP.Mundial.Entidades.Partido", "Partido")
                        .WithMany()
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TUP.Mundial.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partido");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
